In [19]:
import numpy as np

x = np.array([

    [1,-5],
    [-7,21],
    [28, 19]

])

In [20]:
# 1 matrix relu
def naive_relu(x):
  assert len(x.shape) == 2
  x = x.copy()

  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i,j] = max(x[i,j], 0)

  return x

print(naive_relu(x))

[[ 1  0]
 [ 0 21]
 [28 19]]


In [30]:
# 2 matrix addition

y = np.array([
    [2, -4],
    [6, 8],
    [10, -12]
])

def naive_add(x,y):
  assert len(x.shape) == 2
  assert x.shape == y.shape

  x = x.copy()

  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i,j] += y[i,j]

  return x

print(x)
print(y)
print()
print(naive_add(x,y))

[[ 1 -5]
 [-7 21]
 [28 19]]
[[  2  -4]
 [  6   8]
 [ 10 -12]]

[[ 3 -9]
 [-1 29]
 [38  7]]


In [31]:
import time

t0 = time.time()

for _ in range(1000):
  z = x+y
  z = np.maximum(z, 0.)

my_time = time.time() - t0
print(f"{my_time: .2f} s")

for _ in range(1000):
  z = naive_add(x, y)
  z = naive_relu(z)
my_time = time.time() - t0
print(f"{my_time: .2f} s")



 0.01 s
 0.03 s


In [26]:
# 1 matrix and 1 vector addition

y = np.array([4,6])

def naive_add_matrix_and_vector(x, y):
  assert len(x.shape) == 2
  # X = (3,2)
  # y = (2, 1)

  assert x.shape[1] == y.shape[0]

  x = x.copy()

  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i,j] += y[j]

  return x

print(naive_add_matrix_and_vector(x, y))

[[ 5  1]
 [-3 27]
 [32 25]]
