In [15]:
import numpy as np

x = np.array([4,-5, 1, 2, 7]) # (5,1)
y = np.array([6, 10, 2, 3, 16]) # (5,1)

print(x.shape)
print()
print(y.shape)

(5,)

(5,)


In [16]:
# 2 vector dot

def naive_vector_dot(x, y):
  assert len(x.shape) == 1
  assert len(y.shape) == 1
  assert x.shape[0] == y.shape[0]

  z = 0.

  for i in range(x.shape[0]):
    z += x[i] * y[i]
  return z

print(naive_vector_dot(x,y))

94.0


In [19]:
# 1 matrix and 1 vector dot

x = np.array([
    [4,5, 3, 2, 1],
    [0, -3, -4, -6, 7],
    [1,2,4,7,10],
    [19, 24, 22, 28, 37],
    [7, 6, 4, 1, 22]
])

def naive_matrix_vector_dot(x, y):
  assert len(x.shape) == 2
  assert len(y.shape) == 1
  assert x.shape[1] == y.shape[0]

  z = np.zeros(x.shape[0])
  for i in range(x.shape[0]):
    row_x = x[i, :]
    col_y = y
    z[i] = naive_vector_dot(row_x, col_y)

  return z

print(naive_matrix_vector_dot(x, y))

def naive_matrix_vector_dot_longer(x, y):
  assert len(x.shape) == 2
  assert len(y.shape) == 1
  assert x.shape[1] == y.shape[0]

  z = np.zeros(x.shape[0])

  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      z[i] += x[i, j] * y[j]

  return z

print(naive_matrix_vector_dot_longer(x, y))

[ 102.   56.  215. 1074.  465.]
[ 102.   56.  215. 1074.  465.]


In [21]:
# 2 matrices dot
y = np.array([
    [0, -3, -4, -6, 7],
    [4,5, 3, 2, 1],
    [19, 24, 22, 28, 37],
    [1,2,4,7,10],
    [7, 6, 4, 1, 22]
])

def naive_matrix_dot(x, y):
  assert len(x.shape) == 2
  assert len(y.shape) == 2

  assert x.shape[1] == y.shape[0]

  z = np.zeros((x.shape[0], y.shape[1]))

  for i in range(x.shape[0]):
    for j in range(y.shape[1]):
      row_x = x[i,:]
      col_y = y[:, j]
      z[i, j] = naive_vector_dot(row_x, col_y)

  return z

print(naive_matrix_dot(x, y))
print(naive_matrix_dot(x, y).shape)

[[  86.   95.   77.   85.  186.]
 [ -45.  -81.  -93. -153.  -57.]
 [ 161.  177.  158.  169.  447.]
 [ 801.  869.  740.  783. 2065.]
 [ 255.  239.  170.  111.  697.]]
(5, 5)


In [25]:
# tensor reshaping
x = np.array([[0., 1.],
             [2., 3.],
             [4., 5.]])
x.shape


(3, 2)

In [26]:
x.reshape((1, 6))

array([[0., 1., 2., 3., 4., 5.]])

In [27]:
x.reshape((6, 1))

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.]])

In [28]:
x.reshape((2, 3))

array([[0., 1., 2.],
       [3., 4., 5.]])

In [30]:
x = np.zeros((300, 20))
x = np.transpose(x)
x.shape

# x[i: ] -> x[:, i]

(20, 300)