In [2]:
import tensorflow as tf

x = tf.Variable(0.)
with tf.GradientTape() as tape:
  y = 2*x + 3

grad_of_y_wrt_x = tape.gradient(y, x)

print(x)
print(x.shape)
print()
print(grad_of_y_wrt_x)
print(grad_of_y_wrt_x.shape)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.0>
()

tf.Tensor(2.0, shape=(), dtype=float32)
()


In [4]:
x = tf.Variable(tf.random.uniform((2,2)))

with tf.GradientTape() as tape:
  y = 2*x + 3

grad_of_y_wrt_x = tape.gradient(y, x)

print(x)
print(x.shape)
print()
print(grad_of_y_wrt_x)
print(grad_of_y_wrt_x.shape)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0.23312068, 0.9019171 ],
       [0.62587976, 0.4783336 ]], dtype=float32)>
(2, 2)

tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)
(2, 2)


In [12]:
x = tf.random.uniform((2,2))
W = tf.Variable(tf.random.uniform((2,2)))
b = tf.Variable(tf.zeros((2,)))

with tf.GradientTape() as tape:
  y = tf.matmul(x, W) + b

grad_of_y_wrt_W_and_b = tape.gradient(y, [W,b])

print(f"x: {x}")
print(f"x shape: {x.shape}")
print()
print(f"W: {W}")
print(f"W shape: {W.shape}")
print()
print(f"b: {b}")
print(f"b shape: {b.shape}")
print()
print(len(grad_of_y_wrt_W_and_b))
print()
print(grad_of_y_wrt_W_and_b)
print()
print(f"gradient of y wrt to W: {grad_of_y_wrt_W_and_b[0]}")
print()
print(f"gradient of y wrt to b: {grad_of_y_wrt_W_and_b[1]}")

x: [[0.21434045 0.91867304]
 [0.80846965 0.5377463 ]]
x shape: (2, 2)

W: <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0.3866564 , 0.69314873],
       [0.41975403, 0.23881352]], dtype=float32)>
W shape: (2, 2)

b: <tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>
b shape: (2,)

2

[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.0228101, 1.0228101],
       [1.4564193, 1.4564193]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 2.], dtype=float32)>]

gradient of y wrt to W: [[1.0228101 1.0228101]
 [1.4564193 1.4564193]]

gradient of y wrt to b: [2. 2.]
