In [1]:
# TensorFlow: tensors, tensor operations [relu, addition, matmul], and backpropogation
# Keras: layers, models, optimizers, metrics, losses, and training loop

In [2]:
import tensorflow as tf
# All ones or All zeros

x = tf.ones(shape = (3,1))
print(x)

x = tf.zeros(shape = (3,1))
print(x)

tf.Tensor(
[[1.]
 [1.]
 [1.]], shape=(3, 1), dtype=float32)
tf.Tensor(
[[0.]
 [0.]
 [0.]], shape=(3, 1), dtype=float32)


In [3]:
# Random tensors
x = tf.random.normal(shape=(4,2), mean = 0, stddev = 1)
print(x)

x = tf.random.uniform(shape = (4,2), minval = 0, maxval = 1)
print(x)

tf.Tensor(
[[-2.1706066  -1.346727  ]
 [-0.01424817 -0.60558957]
 [-0.6086878   0.07280066]
 [-0.04642203  1.1734228 ]], shape=(4, 2), dtype=float32)
tf.Tensor(
[[0.13886249 0.748147  ]
 [0.16903055 0.95174396]
 [0.34520423 0.9431205 ]
 [0.7222599  0.9187176 ]], shape=(4, 2), dtype=float32)


In [9]:
# Numpy arrays are assignable
import numpy as np
x = np.ones(shape = (2,3))
print(x)
print()
x[0,0] = 0.
print(x)

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 1. 1.]
 [1. 1. 1.]]


In [10]:
x = tf.ones(shape = (2, 3))
x[0,0] = 0.
# Error as TensorFlow tensors are not assignable

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [25]:
v = tf.Variable(initial_value = tf.random.normal(shape = (3,1)))
print(v)
print()

v.assign(tf.ones(shape = (3,1)))
print(v)
print()

v[0,0].assign(3.)
print(v)

v.assign_add(tf.ones(shape = (3,1)))
print(v)
print()
v.assign_sub(tf.ones(shape = (3,1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-0.8754674 ],
       [-1.3892298 ],
       [ 0.49916852]], dtype=float32)>

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [2.],
       [2.]], dtype=float32)>

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>


In [28]:
a = tf.ones(shape = (2,2))
print(a)
print()
b = tf.square(a)
print(b)
print()
c = tf.sqrt(a)
print(c)
print()
d = b+c
print(d)
print()
e = tf.matmul(a, b) # dot product
print(e)
print()
e*=d # element-wise
print(e)



tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)

tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)

tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)

tf.Tensor(
[[4. 4.]
 [4. 4.]], shape=(2, 2), dtype=float32)


In [29]:
input_var = tf.Variable(initial_value = 3.)
with tf.GradientTape() as tape:
  result = tf.square(input_var)
gradient = tape.gradient(result, input_var)

print(result)
print()
print(gradient)

tf.Tensor(9.0, shape=(), dtype=float32)

tf.Tensor(6.0, shape=(), dtype=float32)


In [31]:
input_constant = tf.constant(3.)
with tf.GradientTape() as tape:
  tape.watch(input_constant) # with constant tensor inputs
  result = tf.square(input_constant)
gradient = tape.gradient(result, input_constant)

print(result)
print()
print(gradient)

tf.Tensor(9.0, shape=(), dtype=float32)

tf.Tensor(6.0, shape=(), dtype=float32)


In [32]:
# gradient of the position of an object with regard to time is the speed of that object
# , and the second-order gradient is its acceleration

In [34]:
time = tf.Variable(0.)
with tf.GradientTape() as outer_tape:
  with tf.GradientTape() as inner_tape:
    position = 4.9 * time ** 2
  speed = inner_tape.gradient(position, time)
acceleration = outer_tape.gradient(speed, time)

print(time)
print()
print(position)
print()
print(speed)
print()
print(acceleration)
print()

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.0>

tf.Tensor(0.0, shape=(), dtype=float32)

tf.Tensor(0.0, shape=(), dtype=float32)

tf.Tensor(9.8, shape=(), dtype=float32)

