In [1]:
## Tensors

In [2]:
!pip install torch numpy

In [3]:
import torch
import numpy as np

### Tensor Initialization

In [4]:
# Tensors are similar to NumPy’s ndarrays, 
# except that tensors can run on GPUs or other specialized hardware to accelerate computing.
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [5]:
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [6]:
np_array = np.array(data)
x_np = torch.tensor(np_array)

In [7]:
print(type(x_np))
print(x_np)

<class 'torch.Tensor'>
tensor([[1, 2],
        [3, 4]])


In [8]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data: (shape, dtype)
print(x_ones)

# shape, data type # overrides the datatype of x_data
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.8244, 0.1569],
        [0.1872, 0.8473]])


In [9]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'rand_tensor: {rand_tensor}\n')
print(f'ones_tensor: {ones_tensor}\n')
print(f'zeros_tensor: {zeros_tensor}\n')

rand_tensor: tensor([[0.5729, 0.1624, 0.4289],
        [0.8294, 0.6506, 0.3313]])

ones_tensor: tensor([[1., 1., 1.],
        [1., 1., 1.]])

zeros_tensor: tensor([[0., 0., 0.],
        [0., 0., 0.]])



### Tensor Attributes

In [10]:
tensor = torch.rand(3, 4)

print(f'tensor shape: {tensor.shape}')
print(f'tensor dtype: {tensor.dtype}')
print(f'tensor device: {tensor.device}')

tensor shape: torch.Size([3, 4])
tensor dtype: torch.float32
tensor device: cpu


In [11]:
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else 'cpu'
tensor = tensor.to(device)
print(f'tensor moved to device: {tensor.device}')

tensor moved to device: mps:0


In [12]:
# standard indexing and slicing
tensor = torch.ones(4,4)
tensor[:, 1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [13]:
# joining tensors
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [14]:
t2 = torch.cat([tensor, tensor, tensor], dim = 0)
print(t2)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [15]:
# multiplying tensors (element wise product)
print(f'tensor.mul(tensor): \n {tensor.mul(tensor)}\n')
print()
print(f'tensor * tensor: \n {tensor * tensor}\n')

tensor.mul(tensor): 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


tensor * tensor: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])



In [16]:
# matrix multiplication between two tensors
print(f'tensor.matmul(tensor.T): \n {tensor.matmul(tensor.T)}\n')
print()
print(f'tensor @ tensor.T \n {tensor @ tensor.T}\n')

tensor.matmul(tensor.T): 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])



In [17]:
# in place operations
print(tensor, '\n')
tensor.add_(5)
print(tensor, '\n')

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 



In [18]:
t = torch.ones(5)
print(f't: \n {t} \n')
n = t.numpy()
print(f'n: \n {n} \n')

t: 
 tensor([1., 1., 1., 1., 1.]) 

n: 
 [1. 1. 1. 1. 1.] 



In [19]:
t.add_(1)
print(f't: \n {t} \n')
print(f'n: \n {n} \n')

t: 
 tensor([2., 2., 2., 2., 2.]) 

n: 
 [2. 2. 2. 2. 2.] 



In [20]:
nump = np.ones(5)
tensor_conversion = torch.from_numpy(nump)
print(f'numpy array: \n {nump} \n')
print()
print(f'tensor_conversion: \n {tensor_conversion} \n')

numpy array: 
 [1. 1. 1. 1. 1.] 


tensor_conversion: 
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64) 



In [21]:
np.add(nump, 1, out = nump)
print(f'numpy array: \n {nump} \n')
print()
print(f'tensor_conversion: \n {tensor_conversion} \n')

numpy array: 
 [2. 2. 2. 2. 2.] 


tensor_conversion: 
 tensor([2., 2., 2., 2., 2.], dtype=torch.float64) 



In [22]:
!pip install torchvision

In [23]:
# Weights and biases stored as tensors in PyTorch
from torchvision.models import resnet18, ResNet18_Weights
model = resnet18(weights=ResNet18_Weights.DEFAULT)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /Users/koushalsmodi/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth


100.0%


In [24]:
# forward pass
prediction = model(data)

In [29]:
prediction

tensor([[-0.7014, -0.4653, -0.8959, -1.8184, -0.7532, -0.4057, -0.7294,  0.4205,
          0.3060, -0.7205, -1.3152, -1.0662, -0.4470, -1.2261, -1.0642, -0.8098,
         -0.8706, -0.4116, -0.4584, -0.5554, -1.6871, -1.1511, -1.4792,  0.2052,
         -1.4708, -1.1939, -0.7530, -1.0273, -0.8309, -0.2107, -0.8204, -0.4748,
         -0.3224, -0.9360, -0.9634, -0.5694,  0.5006, -0.7177, -0.4030, -0.1039,
         -0.5291, -0.8214, -1.1775, -0.5997, -0.4769, -0.5354, -0.6034, -0.2995,
         -1.4534, -1.4349, -0.7264,  0.3257, -0.2172, -0.6234, -0.1663, -1.0913,
         -0.3801, -1.5410, -0.5066, -0.4976,  0.9352,  0.1901, -0.2167,  0.0262,
         -0.7954, -0.5571, -0.4198, -0.3957, -0.8194, -1.3365, -1.4014,  0.2589,
         -1.4098, -0.5254, -1.2222, -1.4685, -0.2749, -0.8667, -0.0451,  0.2902,
         -0.7871, -1.7671, -0.1815, -0.9391, -0.4726, -0.3629, -0.0643,  0.1749,
         -0.1929, -1.0688, -1.3955, -1.2902, -2.0922,  0.0517,  0.1731, -2.0166,
         -0.3745, -0.8560, -

In [ ]:
loss = (prediction - labels).sum()
loss.backward() # computes the gradient of the loss

In [ ]:
optim = torch.optim.SGD(model.parameters(), lr = 1e-2 , momentum = 0.9)
optim.step() # initiate gradient descent

### Differentiation in Autograd

In [33]:
import torch 

# parameters of NN
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([4., 6.], requires_grad=True)

# Error = Q
Q = 3*a**3 - b**2

# Gradients of the error wrt parameters
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

print(9*a**2 == a.grad)
print(-2*b == b.grad)

tensor([True, True])
tensor([True, True])


In [34]:
# Exclusion from gradient calculation
from torch import nn, optim

model = resnet18(weights=ResNet18_Weights.DEFAULT)

# freeze all the paramters in the network
for param in model.parameters():
    param.requires_grad = False

# in resnet, the classifier is the last linear layer model.fc
# replace with a new lienar layer
model.fc = nn.Linear(512, 10)

# optimize only the classifier
optimizer = optim.SGD(model.parameters(), lr = 1e-2, momentum=0.9)