In [1]:
## Tensors

In [2]:
!pip install torch numpy

In [3]:
import torch
import numpy as np

### Tensor Initialization

In [4]:
# Tensors are similar to NumPy’s ndarrays, 
# except that tensors can run on GPUs or other specialized hardware to accelerate computing.
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [5]:
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [6]:
np_array = np.array(data)
x_np = torch.tensor(np_array)

In [7]:
print(type(x_np))
print(x_np)

<class 'torch.Tensor'>
tensor([[1, 2],
        [3, 4]])


In [8]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data: (shape, dtype)
print(x_ones)

# shape, data type # overrides the datatype of x_data
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.5199, 0.8447],
        [0.5817, 0.2807]])


In [9]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'rand_tensor: {rand_tensor}\n')
print(f'ones_tensor: {ones_tensor}\n')
print(f'zeros_tensor: {zeros_tensor}\n')

rand_tensor: tensor([[0.3766, 0.2059, 0.5833],
        [0.6453, 0.4763, 0.0805]])

ones_tensor: tensor([[1., 1., 1.],
        [1., 1., 1.]])

zeros_tensor: tensor([[0., 0., 0.],
        [0., 0., 0.]])



### Tensor Attributes

In [10]:
tensor = torch.rand(3, 4)

print(f'tensor shape: {tensor.shape}')
print(f'tensor dtype: {tensor.dtype}')
print(f'tensor device: {tensor.device}')

tensor shape: torch.Size([3, 4])
tensor dtype: torch.float32
tensor device: cpu


In [12]:
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else 'cpu'
tensor = tensor.to(device)
print(f'tensor moved to device: {tensor.device}')

tensor moved to device: mps:0


In [13]:
# standard indexing and slicing
tensor = torch.ones(4,4)
tensor[:, 1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
# joining tensors
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [15]:
t2 = torch.cat([tensor, tensor, tensor], dim = 0)
print(t2)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
# multiplying tensors (element wise product)
print(f'tensor.mul(tensor): \n {tensor.mul(tensor)}\n')
print()
print(f'tensor * tensor: \n {tensor * tensor}\n')

tensor.mul(tensor): 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


tensor * tensor: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])



In [21]:
# matrix multiplication between two tensors
print(f'tensor.matmul(tensor.T): \n {tensor.matmul(tensor.T)}\n')
print()
print(f'tensor @ tensor.T \n {tensor @ tensor.T}\n')

tensor.matmul(tensor.T): 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])



In [22]:
# in place operations
print(tensor, '\n')
tensor.add_(5)
print(tensor, '\n')

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 



In [24]:
t = torch.ones(5)
print(f't: \n {t} \n')
n = t.numpy()
print(f'n: \n {n} \n')

t: 
 tensor([1., 1., 1., 1., 1.]) 

n: 
 [1. 1. 1. 1. 1.] 



In [25]:
t.add_(1)
print(f't: \n {t} \n')
print(f'n: \n {n} \n')

t: 
 tensor([2., 2., 2., 2., 2.]) 

n: 
 [2. 2. 2. 2. 2.] 



In [27]:
nump = np.ones(5)
tensor_conversion = torch.from_numpy(nump)
print(f'numpy array: \n {nump} \n')
print()
print(f'tensor_conversion: \n {tensor_conversion} \n')

numpy array: 
 [1. 1. 1. 1. 1.] 


tensor_conversion: 
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64) 



In [33]:
np.add(nump, 1, out = nump)
print(f'numpy array: \n {nump} \n')
print()
print(f'tensor_conversion: \n {tensor_conversion} \n')

numpy array: 
 [2. 2. 2. 2. 2.] 


tensor_conversion: 
 tensor([2., 2., 2., 2., 2.], dtype=torch.float64) 

