In [ ]:
state_t = 0 # the state at t
for input_t in input_sequence: # iterates over sequence elements
  output_t = f(input_t, state_t)
  state_t = output_t # the previous output becomes the state for the next iteration

In [ ]:
# more-detailed pseudocode for the RNN

state_t = 0
for input_t in input_sequence:
  output_t = activation(dot(W, input_t) + dot(U, state_t) + b)
  state_t = output_t

In [5]:
import numpy as np
timesteps = 42 # number of timesteps in the input sequence
input_features = 32 # dimensionality of the input feature space
output_features = 64 # dimensionality of the output feature space

inputs = np.random.random((timesteps, input_features)) # random noise data: (100, 32)
state_t = np.zeros((output_features,)) # initialize state: an all-zero vector (64, )

# Create random weight matrices
W = np.random.random((output_features, input_features)) # (64, 32)
U = np.random.random((output_features, output_features)) # (32, 1)
b = np.random.random((output_features,)) # (64, 1)

successive_outputs = []
print(inputs)
print()
# input_t is a vector of shape (input_features, ) = (32, 1)
for input_t in inputs:
  print("input_t", input_t)
  output_t = np.tanh(np.dot(W, input_t) + np.dot(U, state_t) + b)
  print("output_t", output_t)
  # Combines the input with the current state (the previous output) to obtain the current output. We use tanh to add non-linearity (we could use any other activation function)
  successive_outputs.append(output_t) # stores this output in a list
  state_t = output_t  # updates the state of the network for the next timestep
  print("state_t", state_t)
final_output_sequence = np.stack(successive_outputs, axis = 0) # the final output is a rank-2 tensor of shape (timesteps, output_features)
print("final_output_sequence", final_output_sequence)


[[0.80974293 0.60995746 0.97852614 ... 0.15828519 0.09600089 0.39643966]
 [0.93084992 0.0645641  0.31186167 ... 0.16134375 0.04987114 0.44338708]
 [0.35765201 0.97782028 0.0408362  ... 0.84026406 0.443062   0.13202856]
 ...
 [0.86348091 0.65295098 0.76681276 ... 0.41745969 0.42537669 0.86032567]
 [0.89311853 0.30252554 0.83234141 ... 0.54367599 0.24306934 0.87704413]
 [0.98178217 0.45378032 0.25661784 ... 0.3223241  0.4984671  0.44085034]]

input_t [0.80974293 0.60995746 0.97852614 0.05330318 0.55053706 0.60171662
 0.95973176 0.28092072 0.65426414 0.32446104 0.3226826  0.99138546
 0.5389491  0.1499928  0.81548869 0.43932565 0.43087823 0.93810818
 0.22032016 0.62782457 0.32846331 0.75885719 0.54100865 0.90464829
 0.55874824 0.36353521 0.18418396 0.30194506 0.86715928 0.15828519
 0.09600089 0.39643966]
output_t [0.99999999 1.         0.99999947 0.99999997 0.99999986 0.99999997
 0.99999995 0.9999999  0.99999998 0.99999979 0.99999995 0.99999987
 0.99999716 0.99999998 0.99999998 0.99999967 