In [1]:
import tensorflow as tf

All-ones and all-zeros

In [2]:
x = tf.ones(shape=(3,1))
print(x)

tf.Tensor(
[[1.]
 [1.]
 [1.]], shape=(3, 1), dtype=float32)


In [3]:
x = tf.zeros(shape=(2,2))
print(x)

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


Random tensors

In [4]:
x = tf.random.normal(shape=(4,2), mean = 0., stddev = 1.)
print(x)

tf.Tensor(
[[ 1.298685   -0.69093573]
 [-0.09203622 -0.777811  ]
 [ 0.3851274   1.2059399 ]
 [ 0.22359763  0.60690844]], shape=(4, 2), dtype=float32)


In [5]:
x = tf.random.uniform(shape=(2,4), minval=0., maxval = 1.)
print(x)

tf.Tensor(
[[0.92243683 0.35930443 0.26914907 0.1349554 ]
 [0.09829843 0.7229626  0.19955397 0.8884442 ]], shape=(2, 4), dtype=float32)


Numpy arrays are assignable while TensorFlow tensors are not assignable

In [8]:
import numpy as np
x = np.ones(shape=(3,2))
x[0,0] = 0
print(x)

[[0. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
x = tf.ones(shape=(3,2))
x[0,0] = 0
# TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

Creating a TensorFlow variable

In [11]:
v = tf.Variable(initial_value=tf.random.normal(shape=(2,4)), mean = 0., stddev = 1.)
print(v)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=float32, numpy=
array([[-0.8542245 , -0.45013875,  0.48726413,  1.5941863 ],
       [ 0.90083516,  0.0554653 , -0.18633617, -0.43474144]],
      dtype=float32)>


Now, assigning a value to a TensorFlow is allowed

In [12]:
v.assign(tf.ones(shape=(2,4)))

<tf.Variable 'UnreadVariable' shape=(2, 4) dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

Assigning a value to a subset of TensorFlow variable

In [14]:
v[0,0].assign(5)
print(v)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=float32, numpy=
array([[5., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>


Using assign_add()

In [18]:
v.assign_add(tf.ones((2,4)))

<tf.Variable 'UnreadVariable' shape=(2, 4) dtype=float32, numpy=
array([[6., 2., 2., 2.],
       [2., 2., 2., 2.]], dtype=float32)>

Gradient Tape advanced

In [26]:
input_var = tf.Variable(initial_value = 3.)
with tf.GradientTape() as tape:
  result = tf.square(input_var)
gradient = tape.gradient(result, input_var)
print(gradient)

tf.Tensor(6.0, shape=(), dtype=float32)


Gradient Tape with constant tensors

In [27]:
input_const = tf.constant(3.)
with tf.GradientTape() as tape:
  tape.watch(input_const)
  result = tf.square(input_const)
gradient = tape.gradient(result, input_const)
print(gradient)

tf.Tensor(6.0, shape=(), dtype=float32)


Using nested gradient tapes for second-order derivatives

In [30]:
time = tf.Variable(0.)
with tf.GradientTape() as outer_tape:
  with tf.GradientTape() as inner_tape:
    position = 4.9 * time ** 2
  speed = inner_tape.gradient(position, time)
acceleration = outer_tape.gradient(speed, time)
print(speed)
print()
print(acceleration)

tf.Tensor(0.0, shape=(), dtype=float32)

tf.Tensor(9.8, shape=(), dtype=float32)
